### PR TITLE
Fixed deprecation warnings from v0.4-rc3

### PR DESCRIPTION
**Pull request by slundberg**
Cleans up all the deprecation issues in v0.4 to give a clean load.

### CODE REVIEW

**Comment by aviks** [comment]
@slundberg Thanks for this, but could you please rebase and force-push the branch again? I'd like to get a successful travis run before merging this.

**Comment by slundberg** [comment]
Will do, thanks for adding travis. I'll sort out the 0.3 issues and then update this request.

**Comment by slundberg** [comment]
Alright, sorry to submit a bad pull request initially! Everything passes now on both 0.3 and 0.4

**Comment by aviks** [comment]
Thanks!

**Pull request merged**
